version: '3.7'

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    volumes:
      - /docker/homeassistant/config:/config
    ports:
      - "8123:8123"
    environment:
      TZ: ${TZ}
    restart: unless-stopped
    networks:
      - external
      - internal
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.141:514"
        tag: "homeassistant"

  mariadb:
    image: mariadb:10.11.2-jammy
    volumes:
      - /docker/mariadb/data:/var/lib/mysql
      - /docker/mariadb/conf:/etc/mysql/conf.d
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      TZ: ${TZ}
    restart: unless-stopped
    networks:
      - internal
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.141:514"
        tag: "mariadb"

  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - /docker/mosquitto/config:/mosquitto/config
      - /docker/mosquitto/data:/mosquitto/data
      - /docker/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      TZ: ${TZ}
    restart: unless-stopped
    networks:
      - external
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.141:514"
        tag: "mosquitto"

  node-red:
    image: nodered/node-red:latest
    volumes:
      - /docker/node-red/data:/data
    ports:
      - "1880:1880"
    environment:
      TZ: ${TZ}
    restart: unless-stopped
    networks:
      - external
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.141:514"
        tag: "node-red"

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    platform: linux/arm64
    volumes:
      - /docker/phpmyadmin/bitnami:/bitnami
    ports:
      - "8088:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      TZ: ${TZ}
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      - mariadb
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.141:514"
        tag: "phpmyadmin"

networks:
  external:
    driver: bridge
  internal:
    driver: bridge
