version: "3.8"

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    volumes:
      - /docker/homeassistant/config:/config
    ports:
      - "8123:8123"
    environment:
      TZ: ${TZ}
    restart: unless-stopped
    networks:
      - external
    depends_on:
      - mosquitto
    logging:
      driver: syslog
      options:
        tag: "homeassistant"

  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - /docker/mosquitto/config:/mosquitto/config
      - /docker/mosquitto/data:/mosquitto/data
      - /docker/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      TZ: ${TZ}
    restart: unless-stopped
    networks:
      - external
    logging:
      driver: syslog
      options:
        tag: "mosquitto"

  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    ports:
      - "8088:80"
    environment:
      PMA_HOST: mariadb-clean
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      TZ: ${TZ}
    restart: unless-stopped
    networks:
      - external
    logging:
      driver: syslog
      options:
        tag: "phpmyadmin"

  unifi-protect-downloader:
    image: unifitoolbox/protect-archiver:latest
    container_name: unifi_protect_downloader
    volumes:
      - /surveillance/unifi:/downloads
    environment:
      - ADDRESS=unifi.local
      - USERNAME=${ui_uname}
      - PASSWORD=${ui_pass}
      - VERIFY_SSL=false
      - CAMERAS=all
      - EVENTS_ONLY=true
      - USE_SUBFOLDERS=true
    restart: unless-stopped
    networks:
      - external
    logging:
      driver: syslog
      options:
        tag: "unifi-protect-downloader"
        
networks:
  external:
    external: true
    name: hass-stack_external
